// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.example.proto;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_proto_GithubApi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_proto_GithubApi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\021com.example.proto\"\265\n\n\tG" +
      "ithubApi\022*\n\020current_user_url\030\001 \001(\tR\020curr" +
      "ent_user_url\022R\n$current_user_authorizati" +
      "ons_html_url\030\002 \001(\tR$current_user_authori" +
      "zations_html_url\022.\n\022authorizations_url\030\003" +
      " \001(\tR\022authorizations_url\022(\n\017code_search_" +
      "url\030\004 \001(\tR\017code_search_url\022,\n\021commit_sea" +
      "rch_url\030\005 \001(\tR\021commit_search_url\022\036\n\nemai" +
      "ls_url\030\006 \001(\tR\nemails_url\022\036\n\nemojis_url\030\007" +
      " \001(\tR\nemojis_url\022\036\n\nevents_url\030\010 \001(\tR\nev" +
      "ents_url\022\034\n\tfeeds_url\030\t \001(\tR\tfeeds_url\022$" +
      "\n\rfollowers_url\030\n \001(\tR\rfollowers_url\022$\n\r" +
      "following_url\030\013 \001(\tR\rfollowing_url\022\034\n\tgi" +
      "sts_url\030\014 \001(\tR\tgists_url\022\030\n\007hub_url\030\r \001(" +
      "\tR\007hub_url\022*\n\020issue_search_url\030\016 \001(\tR\020is" +
      "sue_search_url\022\036\n\nissues_url\030\017 \001(\tR\nissu" +
      "es_url\022\032\n\010keys_url\030\020 \001(\tR\010keys_url\022,\n\021no" +
      "tifications_url\030\021 \001(\tR\021notifications_url" +
      "\022D\n\035organization_repositories_url\030\022 \001(\tR" +
      "\035organization_repositories_url\022*\n\020organi" +
      "zation_url\030\023 \001(\tR\020organization_url\022*\n\020pu" +
      "blic_gists_url\030\024 \001(\tR\020public_gists_url\022&" +
      "\n\016rate_limit_url\030\025 \001(\tR\016rate_limit_url\022&" +
      "\n\016repository_url\030\026 \001(\tR\016repository_url\0224" +
      "\n\025repository_search_url\030\027 \001(\tR\025repositor" +
      "y_search_url\022D\n\035current_user_repositorie" +
      "s_url\030\030 \001(\tR\035current_user_repositories_u" +
      "rl\022 \n\013starred_url\030\031 \001(\tR\013starred_url\022,\n\021" +
      "starred_gists_url\030\032 \001(\tR\021starred_gists_u" +
      "rl\022\032\n\010team_url\030\033 \001(\tR\010team_url\022\032\n\010user_u" +
      "rl\030\034 \001(\tR\010user_url\0226\n\026user_organizations" +
      "_url\030\035 \001(\tR\026user_organizations_url\0224\n\025us" +
      "er_repositories_url\030\036 \001(\tR\025user_reposito" +
      "ries_url\022(\n\017user_search_url\030\037 \001(\tR\017user_" +
      "search_urlB\005P\001\272\002\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_proto_GithubApi_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_proto_GithubApi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_proto_GithubApi_descriptor,
        new java.lang.String[] { "CurrentUserUrl", "CurrentUserAuthorizationsHtmlUrl", "AuthorizationsUrl", "CodeSearchUrl", "CommitSearchUrl", "EmailsUrl", "EmojisUrl", "EventsUrl", "FeedsUrl", "FollowersUrl", "FollowingUrl", "GistsUrl", "HubUrl", "IssueSearchUrl", "IssuesUrl", "KeysUrl", "NotificationsUrl", "OrganizationRepositoriesUrl", "OrganizationUrl", "PublicGistsUrl", "RateLimitUrl", "RepositoryUrl", "RepositorySearchUrl", "CurrentUserRepositoriesUrl", "StarredUrl", "StarredGistsUrl", "TeamUrl", "UserUrl", "UserOrganizationsUrl", "UserRepositoriesUrl", "UserSearchUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
