// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.example.proto;

public interface GithubApiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.proto.GithubApi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string current_user_url = 1[json_name = "current_user_url"];</code>
   */
  java.lang.String getCurrentUserUrl();
  /**
   * <code>string current_user_url = 1[json_name = "current_user_url"];</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserUrlBytes();

  /**
   * <code>string current_user_authorizations_html_url = 2[json_name = "current_user_authorizations_html_url"];</code>
   */
  java.lang.String getCurrentUserAuthorizationsHtmlUrl();
  /**
   * <code>string current_user_authorizations_html_url = 2[json_name = "current_user_authorizations_html_url"];</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserAuthorizationsHtmlUrlBytes();

  /**
   * <code>string authorizations_url = 3[json_name = "authorizations_url"];</code>
   */
  java.lang.String getAuthorizationsUrl();
  /**
   * <code>string authorizations_url = 3[json_name = "authorizations_url"];</code>
   */
  com.google.protobuf.ByteString
      getAuthorizationsUrlBytes();

  /**
   * <code>string code_search_url = 4[json_name = "code_search_url"];</code>
   */
  java.lang.String getCodeSearchUrl();
  /**
   * <code>string code_search_url = 4[json_name = "code_search_url"];</code>
   */
  com.google.protobuf.ByteString
      getCodeSearchUrlBytes();

  /**
   * <code>string commit_search_url = 5[json_name = "commit_search_url"];</code>
   */
  java.lang.String getCommitSearchUrl();
  /**
   * <code>string commit_search_url = 5[json_name = "commit_search_url"];</code>
   */
  com.google.protobuf.ByteString
      getCommitSearchUrlBytes();

  /**
   * <code>string emails_url = 6[json_name = "emails_url"];</code>
   */
  java.lang.String getEmailsUrl();
  /**
   * <code>string emails_url = 6[json_name = "emails_url"];</code>
   */
  com.google.protobuf.ByteString
      getEmailsUrlBytes();

  /**
   * <code>string emojis_url = 7[json_name = "emojis_url"];</code>
   */
  java.lang.String getEmojisUrl();
  /**
   * <code>string emojis_url = 7[json_name = "emojis_url"];</code>
   */
  com.google.protobuf.ByteString
      getEmojisUrlBytes();

  /**
   * <code>string events_url = 8[json_name = "events_url"];</code>
   */
  java.lang.String getEventsUrl();
  /**
   * <code>string events_url = 8[json_name = "events_url"];</code>
   */
  com.google.protobuf.ByteString
      getEventsUrlBytes();

  /**
   * <code>string feeds_url = 9[json_name = "feeds_url"];</code>
   */
  java.lang.String getFeedsUrl();
  /**
   * <code>string feeds_url = 9[json_name = "feeds_url"];</code>
   */
  com.google.protobuf.ByteString
      getFeedsUrlBytes();

  /**
   * <code>string followers_url = 10[json_name = "followers_url"];</code>
   */
  java.lang.String getFollowersUrl();
  /**
   * <code>string followers_url = 10[json_name = "followers_url"];</code>
   */
  com.google.protobuf.ByteString
      getFollowersUrlBytes();

  /**
   * <code>string following_url = 11[json_name = "following_url"];</code>
   */
  java.lang.String getFollowingUrl();
  /**
   * <code>string following_url = 11[json_name = "following_url"];</code>
   */
  com.google.protobuf.ByteString
      getFollowingUrlBytes();

  /**
   * <code>string gists_url = 12[json_name = "gists_url"];</code>
   */
  java.lang.String getGistsUrl();
  /**
   * <code>string gists_url = 12[json_name = "gists_url"];</code>
   */
  com.google.protobuf.ByteString
      getGistsUrlBytes();

  /**
   * <code>string hub_url = 13[json_name = "hub_url"];</code>
   */
  java.lang.String getHubUrl();
  /**
   * <code>string hub_url = 13[json_name = "hub_url"];</code>
   */
  com.google.protobuf.ByteString
      getHubUrlBytes();

  /**
   * <code>string issue_search_url = 14[json_name = "issue_search_url"];</code>
   */
  java.lang.String getIssueSearchUrl();
  /**
   * <code>string issue_search_url = 14[json_name = "issue_search_url"];</code>
   */
  com.google.protobuf.ByteString
      getIssueSearchUrlBytes();

  /**
   * <code>string issues_url = 15[json_name = "issues_url"];</code>
   */
  java.lang.String getIssuesUrl();
  /**
   * <code>string issues_url = 15[json_name = "issues_url"];</code>
   */
  com.google.protobuf.ByteString
      getIssuesUrlBytes();

  /**
   * <code>string keys_url = 16[json_name = "keys_url"];</code>
   */
  java.lang.String getKeysUrl();
  /**
   * <code>string keys_url = 16[json_name = "keys_url"];</code>
   */
  com.google.protobuf.ByteString
      getKeysUrlBytes();

  /**
   * <code>string notifications_url = 17[json_name = "notifications_url"];</code>
   */
  java.lang.String getNotificationsUrl();
  /**
   * <code>string notifications_url = 17[json_name = "notifications_url"];</code>
   */
  com.google.protobuf.ByteString
      getNotificationsUrlBytes();

  /**
   * <code>string organization_repositories_url = 18[json_name = "organization_repositories_url"];</code>
   */
  java.lang.String getOrganizationRepositoriesUrl();
  /**
   * <code>string organization_repositories_url = 18[json_name = "organization_repositories_url"];</code>
   */
  com.google.protobuf.ByteString
      getOrganizationRepositoriesUrlBytes();

  /**
   * <code>string organization_url = 19[json_name = "organization_url"];</code>
   */
  java.lang.String getOrganizationUrl();
  /**
   * <code>string organization_url = 19[json_name = "organization_url"];</code>
   */
  com.google.protobuf.ByteString
      getOrganizationUrlBytes();

  /**
   * <code>string public_gists_url = 20[json_name = "public_gists_url"];</code>
   */
  java.lang.String getPublicGistsUrl();
  /**
   * <code>string public_gists_url = 20[json_name = "public_gists_url"];</code>
   */
  com.google.protobuf.ByteString
      getPublicGistsUrlBytes();

  /**
   * <code>string rate_limit_url = 21[json_name = "rate_limit_url"];</code>
   */
  java.lang.String getRateLimitUrl();
  /**
   * <code>string rate_limit_url = 21[json_name = "rate_limit_url"];</code>
   */
  com.google.protobuf.ByteString
      getRateLimitUrlBytes();

  /**
   * <code>string repository_url = 22[json_name = "repository_url"];</code>
   */
  java.lang.String getRepositoryUrl();
  /**
   * <code>string repository_url = 22[json_name = "repository_url"];</code>
   */
  com.google.protobuf.ByteString
      getRepositoryUrlBytes();

  /**
   * <code>string repository_search_url = 23[json_name = "repository_search_url"];</code>
   */
  java.lang.String getRepositorySearchUrl();
  /**
   * <code>string repository_search_url = 23[json_name = "repository_search_url"];</code>
   */
  com.google.protobuf.ByteString
      getRepositorySearchUrlBytes();

  /**
   * <code>string current_user_repositories_url = 24[json_name = "current_user_repositories_url"];</code>
   */
  java.lang.String getCurrentUserRepositoriesUrl();
  /**
   * <code>string current_user_repositories_url = 24[json_name = "current_user_repositories_url"];</code>
   */
  com.google.protobuf.ByteString
      getCurrentUserRepositoriesUrlBytes();

  /**
   * <code>string starred_url = 25[json_name = "starred_url"];</code>
   */
  java.lang.String getStarredUrl();
  /**
   * <code>string starred_url = 25[json_name = "starred_url"];</code>
   */
  com.google.protobuf.ByteString
      getStarredUrlBytes();

  /**
   * <code>string starred_gists_url = 26[json_name = "starred_gists_url"];</code>
   */
  java.lang.String getStarredGistsUrl();
  /**
   * <code>string starred_gists_url = 26[json_name = "starred_gists_url"];</code>
   */
  com.google.protobuf.ByteString
      getStarredGistsUrlBytes();

  /**
   * <code>string team_url = 27[json_name = "team_url"];</code>
   */
  java.lang.String getTeamUrl();
  /**
   * <code>string team_url = 27[json_name = "team_url"];</code>
   */
  com.google.protobuf.ByteString
      getTeamUrlBytes();

  /**
   * <code>string user_url = 28[json_name = "user_url"];</code>
   */
  java.lang.String getUserUrl();
  /**
   * <code>string user_url = 28[json_name = "user_url"];</code>
   */
  com.google.protobuf.ByteString
      getUserUrlBytes();

  /**
   * <code>string user_organizations_url = 29[json_name = "user_organizations_url"];</code>
   */
  java.lang.String getUserOrganizationsUrl();
  /**
   * <code>string user_organizations_url = 29[json_name = "user_organizations_url"];</code>
   */
  com.google.protobuf.ByteString
      getUserOrganizationsUrlBytes();

  /**
   * <code>string user_repositories_url = 30[json_name = "user_repositories_url"];</code>
   */
  java.lang.String getUserRepositoriesUrl();
  /**
   * <code>string user_repositories_url = 30[json_name = "user_repositories_url"];</code>
   */
  com.google.protobuf.ByteString
      getUserRepositoriesUrlBytes();

  /**
   * <code>string user_search_url = 31[json_name = "user_search_url"];</code>
   */
  java.lang.String getUserSearchUrl();
  /**
   * <code>string user_search_url = 31[json_name = "user_search_url"];</code>
   */
  com.google.protobuf.ByteString
      getUserSearchUrlBytes();
}
